### ISSUE TITLE
Fix it

### ISSUE THREAD

**Issue by jwgmeligmeyling** [StephanMeijer/powerdmenu#2]
```
/usr/lib/node_modules/powerdmenu/lib/powerdmenu.js:25
        command = content.match(/Exec=(.*)/)[1].replace(/\%([A-Za-z])/g, '');
                                            ^
TypeError: Cannot read property '1' of null
    at /usr/lib/node_modules/powerdmenu/lib/powerdmenu.js:25:45
    at Array.forEach (native)
    at command (/usr/lib/node_modules/powerdmenu/lib/powerdmenu.js:21:9)
    at Array.forEach (native)
    at Object.<anonymous> (/usr/lib/node_modules/powerdmenu/lib/powerdmenu.js:17:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```
- NodeJS `v0.10.38`

**Comment by StephanMeijer** [comment]
@jwgmeligmeyling Thanks for the headsup. Back when I wrote crap as code..

**Comment by jwgmeligmeyling** [comment]
🤣

**Comment by StephanMeijer** [comment]
Closing this crap.
